%YAML:1.0
---
Cam_Width: 1280
Cam_Height: 480
CamL_id: 2
CamR_id: 4
board_w: 9
board_h: 6
square_size: 2.4
output_path: "../data/"
estimateZ_videoFileL: "stereoL-001.mp4"
estimateZ_videoFileR: "stereoR-001.mp4"
estimateZ_validDistanceStart: 30
estimateZ_validDistanceEnd: 110
